getwd()
install.packages("tm")
install.packages("wordcloud")
library(tm)
library(wordcloud) 
text <- readLines(file.choose())
docs <- Corpus(VectorSource(text))
docs <- tm_map(docs,tolower)
docs <- tm_map(docs,removeWords,stopwords("english"))
docs <- tm_map(docs,removeNumbers)
docs <- tm_map(docs,removePunctuation)
docs <- tm_map(docs,stripWhitespace)
docs <- tm_map(docs,stemDocument)
#text_tokens(text, stemmer = "en") # english stemmer

dts<-TermDocumentMatrix(docs)
m<-as.matrix(dts)
v<-sort(rowSums(m),decreasing=TRUE)
d<-data.frame(word=names(v),freq=v)
head(d,10)
wordcloud(d$word,freq=d$freq,min.freq=1,max.words=40,random.order=FALSE,rot.per=0.35,color=brewer.pal(8,"Dark2"))